ai:
  provider: ollama # 或 openai
  model: deepseek-r1:1.5b # Ollama已安装的模型
  baseUrl: http://127.0.0.1:11434
# 平台配置  
platform:
  type: github # 或 github
  token: 
  
# # 通知配置
# notifications:
#   gitlab_comment: true
#   wecom:
#     enabled: false
#     webhook: YOUR_WEBHOOK_URL
